"""add is_online to user

Revision ID: 274e92ebc845
Revises: 202406_last_seen_addition
Create Date: 2025-05-16 13:23:11.715589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274e92ebc845'
down_revision = '202406_last_seen_addition'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_online', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_online')
    # ### end Alembic commands ###
